name: kopma
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  intl: ^0.20.2
  shared_preferences: ^2.0.15
  fl_chart: ^0.71.0
  pdf: ^3.11.3
  date_time_format: ^2.0.1
  localization: ^2.1.1
  provider: ^6.1.5
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  file_picker: ^10.1.2
  firebase_core_web: ^2.22.0
  firebase_auth_web: ^5.14.2
  cloud_firestore_web: ^4.4.6
  excel: ^2.0.6
  path_provider: ^2.1.1
  permission_handler: ^11.3.0
  syncfusion_flutter_xlsio: ^29.1.40
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logokopma.png